
import __ASTRO_IMAGE_IMPORT_54xNy from "../../assets/php-gdb.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fextreme-debugging-in-php.md";
import __ASTRO_IMAGE_IMPORT_AQuqE from "../../assets/hexplore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md";
import __ASTRO_IMAGE_IMPORT_Z2cjCR from "../../assets/hexplore-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md";
import __ASTRO_IMAGE_IMPORT_ZrJP82 from "../../assets/hexplore-glore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_14NbP8 from "../../assets/st1-file-structure-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_ZMHCRq from "../../assets/hexplore-warrior-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_KAFlw from "../../assets/hexplore-2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_Z1KNWzn from "../../assets/procrastination.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fovercoming-procrastination-frustration-code-stagnation.md";
import __ASTRO_IMAGE_IMPORT_ZCSdbo from "../../assets/hive-mind.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Funtil-it-bleeds-hive-mind-programming.md";
export default new Map([["../../assets/php-gdb.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fextreme-debugging-in-php.md", __ASTRO_IMAGE_IMPORT_54xNy], ["../../assets/hexplore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md", __ASTRO_IMAGE_IMPORT_AQuqE], ["../../assets/hexplore-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md", __ASTRO_IMAGE_IMPORT_Z2cjCR], ["../../assets/hexplore-glore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_ZrJP82], ["../../assets/st1-file-structure-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_14NbP8], ["../../assets/hexplore-warrior-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_ZMHCRq], ["../../assets/hexplore-2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_KAFlw], ["../../assets/procrastination.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fovercoming-procrastination-frustration-code-stagnation.md", __ASTRO_IMAGE_IMPORT_Z1KNWzn], ["../../assets/hive-mind.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Funtil-it-bleeds-hive-mind-programming.md", __ASTRO_IMAGE_IMPORT_ZCSdbo]]);
		