
import __ASTRO_IMAGE_IMPORT_1ljb7A from "../../assets/extreme-debugging-in-php-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fextreme-debugging-in-php.md";
import __ASTRO_IMAGE_IMPORT_Z1KNWzn from "../../assets/procrastination.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fovercoming-procrastination-frustration-code-stagnation.md";
import __ASTRO_IMAGE_IMPORT_AQuqE from "../../assets/hexplore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md";
import __ASTRO_IMAGE_IMPORT_Z2cjCR from "../../assets/hexplore-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md";
import __ASTRO_IMAGE_IMPORT_ZulSrA from "../../assets/hexplore-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-3-ai-augmented.md";
import __ASTRO_IMAGE_IMPORT_ZrJP82 from "../../assets/hexplore-glore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_14NbP8 from "../../assets/st1-file-structure-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_ZMHCRq from "../../assets/hexplore-warrior-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_KAFlw from "../../assets/hexplore-2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md";
import __ASTRO_IMAGE_IMPORT_1C70o1 from "../../assets/security-is-not-a-feature-its-the-floor-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecurity-is-not-a-feature-its-the-floor.md";
import __ASTRO_IMAGE_IMPORT_j8vmD from "../../assets/the-power-of-post-mortems-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-power-of-post-mortems.md";
import __ASTRO_IMAGE_IMPORT_ZCSdbo from "../../assets/hive-mind.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Funtil-it-bleeds-hive-mind-programming.md";
import __ASTRO_IMAGE_IMPORT_2nDddv from "../../assets/whether-you-can.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhether-you-can-is-learnable-the-issue-is-whether-you-want-to.md";
export default new Map([["../../assets/extreme-debugging-in-php-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fextreme-debugging-in-php.md", __ASTRO_IMAGE_IMPORT_1ljb7A], ["../../assets/procrastination.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fovercoming-procrastination-frustration-code-stagnation.md", __ASTRO_IMAGE_IMPORT_Z1KNWzn], ["../../assets/hexplore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md", __ASTRO_IMAGE_IMPORT_AQuqE], ["../../assets/hexplore-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-1.md", __ASTRO_IMAGE_IMPORT_Z2cjCR], ["../../assets/hexplore-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-3-ai-augmented.md", __ASTRO_IMAGE_IMPORT_ZulSrA], ["../../assets/hexplore-glore.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_ZrJP82], ["../../assets/st1-file-structure-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_14NbP8], ["../../assets/hexplore-warrior-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_ZMHCRq], ["../../assets/hexplore-2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freverse-engineering-hexplore-2.md", __ASTRO_IMAGE_IMPORT_KAFlw], ["../../assets/security-is-not-a-feature-its-the-floor-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecurity-is-not-a-feature-its-the-floor.md", __ASTRO_IMAGE_IMPORT_1C70o1], ["../../assets/the-power-of-post-mortems-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-power-of-post-mortems.md", __ASTRO_IMAGE_IMPORT_j8vmD], ["../../assets/hive-mind.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Funtil-it-bleeds-hive-mind-programming.md", __ASTRO_IMAGE_IMPORT_ZCSdbo], ["../../assets/whether-you-can.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhether-you-can-is-learnable-the-issue-is-whether-you-want-to.md", __ASTRO_IMAGE_IMPORT_2nDddv]]);
		