links:
  github: https://github.com/mistericy
  linkedin: https://www.linkedin.com/in/akoutroulis  

sidebar: right
widgets:
  - recent_posts
  - category 
  - tagcloud
  - archive

banner: ./../images/front.webp
favicon: images/favicon.png