links:
  github: https://github.com/mistericy
  linkedin: https://www.linkedin.com/in/akoutroulis

copyright: >
  Made with ❤️ and ☕ by <a href="https://github.com/mistericy">Alexandros Koutroulis</a>.
  Using <a href="https://hexo.io">Hexo</a> and <a href="https://github.com/hexojs/hexo-theme-landscape">Landscape</a> theme

sidebar: right
widgets:
  - recent_posts
  - category 
  - tagcloud
  - archive

banner: ./../images/front.webp
favicon: images/favicon.png